---
############################
# etcd Default Settings
############################
etcd_user: etcd
etcd_group: etcd
etcd_install_dir: /usr/local/bin
etcd_data_dir: /var/lib/etcd
etcd_confg_dir: /etc/etcd

etcd_use_ips: True
etcd_iface_public: '{{ etcd_network_iface | default("all") }}'
etcd_iface_cluster: '{{ etcd_network_iface | default("default") }}'
etcd_port_client: 2379
etcd_port_peer: 2380

etcd_launch: True

etcd_enable_v2: True # Accept etcd V2 client requests

etcd_scheme: "{% if etcd_secure %}https{% else %}http{% endif %}://"
etcd_cluster: "{% for host in groups[etcd_master_group_name] %}{{ hostvars[host]['ansible_fqdn'] }}={{ etcd_scheme }}{{ hostvars[host]['etcd_address_cluster'] }}:{{ etcd_port_peer }}{% if not loop.last %},{% endif %}{% endfor %}"

etcd_cluster_data_dir: '{{ etcd_data_dir }}/{{ etcd_cluster_name }}.etcd'
etcd_cluster_pki_dir: '{{ etcd_data_dir }}/{{ etcd_cluster_name }}.pki'


