- name: deploy /etc/hosts template
  template:
    src: etc_hosts.j2
    dest: "{{ etc_hosts_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: etc_hosts_add_extra_entries|bool

- include_tasks: install_minio.yaml
  tags:
    - minio
    - ignore_minio
