---
- name: Prepare node
  gather_facts: yes
  hosts: all
  vars:
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }}"

  tasks:
    - name: Enable EPEL
      dnf:
        name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
        state: present
        disable_gpg_check: yes
      when: not use_local_files|bool
      tags:
        - packages
 
    - name: Install EPEL package if repository is enabled
      package:
        name:
          - epel-release
        state: present
      when: not use_local_files|bool
      tags:
        - packages

    - name: Install base packages for your convinience
      package:
        name:
          - vim
          - wget
          - jq
        state: present
      tags:
        - packages

- name: configuring lab environment for Quay HA
  gather_facts: yes
  hosts:
    - psql
  vars_files:
    - ../vaults/quay_auth.vault
  collections:
    - community.general.docker_login
  roles:
    - deploy_quay_ha
